---
# tasks

- name: Install necessary packages
  import_tasks: packages.yml

- name: Apply required SELinux booleans
  import_tasks: selinux_boolean.yml

- name: Create the users for kojid
  import_tasks: users.yml

- name: Ensure Storage is ready
  import_tasks: storage.yml

- name: Configure kojid
  import_tasks: config.yml
